### ISSUE TITLE
Problem in plugin (not in script)

### ISSUE THREAD

**Issue by NettaBen** [arc2qgis/lyrxtoqml#6]
2019-04-09T16:33:39     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~2/apps/qgis/./python/plugins\qlyrx\qlyrx.py", line 635, in run
              self.apply_lyrx_symbols(layer, j_data, geometry_general_type_str)
              File "C:/OSGEO4~2/apps/qgis/./python/plugins\qlyrx\qlyrx.py", line 569, in apply_lyrx_symbols
              symbol = self.parseCharacterFill(charSl, max_size)
             TypeError: parseCharacterFill() takes 2 positional arguments but 3 were given

**Comment by bogind** [comment]
fixed with commit 53,
currently supporting character fill and point symbols.
